desbloqueo_temporal_temperature_setpoint:
  sequence:
  - variables:
      was_locked: '{{ is_state(''input_boolean.block_tsetpoint'', ''on'') }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ was_locked }}'
      sequence:
      - target:
          entity_id: input_boolean.block_tsetpoint
        action: input_boolean.turn_off
  mode: restart
  alias: unlock_temperature_setpoint
  description: desbloqueo del temperature setpoint
'1765478648749':
  sequence:
  - variables:
      was_unlocked: '{{ is_state(''input_boolean.block_tsetpoint'', ''off'') }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ was_unlocked }}'
      sequence:
      - target:
          entity_id: input_boolean.block_tsetpoint
        action: input_boolean.turn_on
  mode: restart
  alias: lock_temperature_setpoint
  description: bloqueo del temperature setpoint
'1767359181214':
  alias: play_santvi_radio_random_minutes
  description: pone en marcha la radio sant vicen√ß de montalt durante unos minutos
    (aleatorio entre un maximo=59 min y un minimo) y, pasado ese tiempo, la apaga.
  fields:
    media_player:
      name: Media Player
      default: media_player.kitchen_speaker
      selector:
        entity:
          domain: media_player
    volume_level:
      name: Volume level
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
    media_content_id:
      name: Media content
      default: media-source://radio_browser/dd39399b-e164-4e98-be93-58a4b0011691
      selector:
        text:
  sequence:
  - target:
      entity_id: '{{ media_player }}'
    data:
      volume_level: '{{ volume_level }}'
    action: media_player.volume_set
  - target:
      entity_id: '{{ media_player }}'
    data:
      media:
        media_content_id: '{{ media_content_id }}'
        media_content_type: music
        metadata: {}
    action: media_player.play_media
  - action: timer.start
    metadata: {}
    target:
      entity_id: timer.timer1
    data:
      duration:
        minutes: '{{ range(25, 60) | random}}'
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - timer.timer1
      from:
      - active
      to:
      - idle
  - target:
      entity_id: '{{ media_player }}'
    action: media_player.media_stop
turnon_ligth_minutes:
  fields:
    lampara_balcon:
      selector:
        entity: {}
      default: switch.shelly1pmminig3_d0cf13cc2b6c
    lampara_recibidor:
      selector:
        entity: {}
      default: switch.shelly1pmminig3_d0cf13cf22a0
  sequence:
  - target:
      entity_id: '{{ lampara_balcon  }}'
    action: switch.turn_on
  - target:
      entity_id: '{{ lampara_recibidor  }}'
    action: switch.turn_on
  - action: timer.start
    metadata: {}
    target:
      entity_id:
      - timer.timer_light_balcom
    data:
      duration:
        minutes: '{{ range(1, 3) | random}}'
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - timer.timer_light_balcom
      from:
      - active
      to:
      - idle
  - target:
      entity_id: '{{ lampara_balcon  }}'
    action: switch.turn_off
  - target:
      entity_id: '{{ lampara_recibidor  }}'
    action: switch.turn_off
  alias: turnon_ligths_minutes
  description: alimenta la luz durante unos minutos (aleatorio entre un maximo=59
    min y un minimo) y, pasado ese tiempo, la apaga.
